; This file contains equates to include in .asm file.

sample1_xI EQU DWORD PTR -16
sample1_yR EQU QWORD PTR -12
sample1_pathS EQU DWORD PTR -4
ackerI_mI EQU DWORD PTR -8
ackerI_nI EQU DWORD PTR -4
strip1S_xS EQU DWORD PTR -4
strip2S_xS EQU DWORD PTR -4
issue_errI EQU DWORD PTR -4
error_errI EQU DWORD PTR -4
uppercaseS_xS EQU DWORD PTR -4
showpositions1_posI EQU DWORD PTR -4
showpositions2_posI EQU DWORD PTR -4
rootR_aR EQU QWORD PTR -24
rootR_bR EQU QWORD PTR -16
rootR_cR EQU QWORD PTR -8
